name: Review PR with OpenAI GPT model

on:
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review, review_requested ]

jobs:
  auto_review:
    name: Review PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Review PR and make comment
        run: |
          source .env/bin/activate
          LINK="LINK=https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}"
          echo $LINK | tr '[:upper:]' '[:lower:]'>> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ github.token }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          python review.py
